### ISSUE TITLE
Extremely slow insertion and huge file size

### ISSUE THREAD

**Issue by chertov** [khonsulabs/nebari#38]
Hi! I'm trying to use nebari storage in a very simple mode to keep a metrics data for a minute per key.
my simple demo:
```Rust
pub fn nebari_test() -> Result<(), anyhow::Error> {
    let path = "db.nebari";
    std::fs::remove_file(path);
    let state = nebari::tree::State::default();
    let context = nebari::Context::default();
    let mut tree = nebari::tree::TreeFile::<nebari::tree::Unversioned, nebari::io::fs::StdFile>::write(path, state, &context, None)?;
    
    let value = [0u8; 0].to_vec();
    
    let mut keys_count = 0;
    let mut keys_size = 0;
    let mut values_size = 0;
    
    let now = std::time::Instant::now();
    for hour in 0..24 {
        for minute in 0..60 {
            for metric in 0..50 {
                let metric = format!("metric_{metric}");
                let key = format!("{metric}:h{hour}:m{minute}");
                keys_size += key.as_bytes().len();
                values_size += value.len();
                tree.set(None, key, value.clone());
                keys_count += 1;
            }
        }
    }
    tree.commit();
    println!("elapsed:        {}s", now.elapsed().as_secs());
    println!("keys_count:     {}", keys_count);
    println!("keys_size:      {}", keys_size);
    use std::os::unix::fs::MetadataExt;
    let meta = std::path::Path::new(path).metadata()?;
    println!("file size:      {}", meta.size());
    Ok(())
}
```

On my macbook arm64 M1 Pro, nebari = "0.3.1" i have this result:
```
elapsed:        372s
keys_count:     72_000
keys_size:      1_167_600
file size:      4_961_529_211
```
After compacting the file size is ~2.8Мб, but compact consumes ```mut self```, i can't compact tree every insert.
I'm looking an embedded rust database for IoT devices with sdcard storage and 64Mb RAM.
Nebari looks like a good solution, but why is it so slowly and the db file so huge?
Could this be incorrect behavior?

for example, this test on another databases:
```
db          time       size
nebari      372s       4_961_529_211 bytes, 2_886_779 bytes after compacting
sled        17s       ~4_718_592 bytes
rocksdb     0.577s    ~2_752_134 bytes
jammdb      1.511s     8_912_896 bytes
siamesedb   4.311s    ~140Мб
```

**Comment by ecton** [comment]
I had a thought that was puzzling me about this comment:

> After compacting the file size is ~2.8Мб, but compact consumes mut self, i can't compact tree every insert.

Originally I thought you were saying it was too slow to compact (which I would not recommend doing after every insert. It should be done periodically, as-needed). However, the reason you gave was that it consumes self.

It [takes the file by-value but also returns one as well](https://docs.rs/nebari/latest/nebari/tree/struct.TreeFile.html#method.compact). This is done because the compact operation needs exclusive ownership over the file so that it can do an atomic swap after the compact operation finishes.

You can call it over and over without manually reopening the file like this:

```rust
file = file.compact(&manager, None)?;
```

Ultimately, Nebari's TreeFile is much lower-level than Sled is, and it also provides different guarantees. Sled batches writes to disk, whereas Nebari leaves that behavior to you to implement. This is what allows `TreeFile` to almost be no_std today, while Sled almost certainly never have a way to run in no_std.

**Comment by chertov** [comment]
@ecton Thanks for the detailed explanation! I figured out how it works. I checked sled with flush after every insert and it very slowly.. nebari is more faster!
On weak devices such as ipcams it is very difficult to use databases. It is necessary to minimize the number of write operations to the SD card. As well as the number of files. Due to the large number of files, the FAT32 file system cannot quickly delete data. For jpg timelapses, I'm using direct writing to tar archives (it's a very simple format), but I would like to have a suitable key-value store for metrics, metadata, videoanalytic data. Perhaps without ACID guarantees, but with less overhead in terms of volume and speed.

**Comment by ecton** [comment]
Nebari may not be a great solution for that use case in such an environment. It's one of the concerns I have about trying to market BonsaiDb to specific workloads -- and metrics ingestion is one of them. By leveraging an in-memory queue to batch writes, I'm hoping to alleviate most of those concerns. But in a more limited environment, it just isn't going to be the best fit compared to some other databases.

I may try to bring some sort of caching layer similar to what I've designed for BonsaiDb to Nebari -- originally I didn't expect Nebari would end up being as interesting to other people as it has turned out to be. Right now it's mostly implementing just the needs of BonsaiDb, but over time I can now see it growing into its own database that fits some people's needs better than a full-featured database like BonsaiDb.

Thank you for trying out Nebari and reporting your findings!
